#!/bin/bash

# Get the aliases and functions
if [ -f ~/.bashrc ]; then
    . ~/.bashrc
fi

# User specific environment and startup programs
PATH=$PATH:$HOME/.local/bin:$HOME/bin
export PATH

export GMOCK_DIR=$HOME/build/gmock
export GTEST_DIR=$GMOCK_DIR/gtest
export GOPATH=$HOME/code/go
export PATH=$PATH:$GOPATH/bin
