#!/bin/bash

source /usr/share/git/git-prompt.sh
export GIT_PS1_SHOWDIRTYSTATE=true
export GIT_PS1_SHOWUNTRACKEDFILES=true

export PS1='\e[0;34m\w\e[0m$(__git_ps1 " \e[0;32m(%s)\e[0m")\n\$ '

export EDITOR=vim
export VISUAL=$EDITOR
export PATH=$PATH:$HOME/.local/bin
# export PATH=$PATH:$HOME/opt/anaconda2/bin
# export PATH=$PATH:$HOME/opt/elixir/bin

# eval "$(stack --bash-completion-script stack)"

svtplay_dl_to_mpv() {
    if [ -z "$1" ]
    then
        echo 'mpvsvt: error: missing url argument'
    else
        mpv --really-quiet $(svtplay-dl -g "$1")
    fi
}

aspell_pipe_string() {
    printf $1 | aspell -a
}

alias ls='ls -h --color=auto --group-directories-first'
alias ll='ls -lh'
alias grep='grep --color=auto'
alias cp='cp -i -v'
alias mv='mv -i -v'
alias rm='rm -i -v'
alias ydl='youtube-dl --prefer-free-formats -o "~/multimedia/videos/web/%(title)s.%(ext)s"'
alias mpvsvt=svtplay_dl_to_mpv
alias spellcheck=aspell_pipe_string
alias ..='cd ..'
