#!/bin/bash

# if not running interactively, don't do anything
[[ $- != *i* ]] && return

PS1="\[\e[00;37m\]\W\$ \[\e[0m\]"

if [ -f ~/.bash_aliases ]; then
    . ~/.bash_aliases
fi

export EDITOR=/usr/bin/vim
export VISUAL=$EDITOR
# gpg agent
export GPG_TTY=$(tty)
# golang
export GOROOT=/usr/lib/go
export GOPATH=$HOME/Code/Go
export PATH=$PATH:$GOPATH/bin
