#!/bin/bash

# Get the aliases and functions
if [ -f ~/.bashrc ]; then
    . ~/.bashrc
fi

# User specific environment and startup programs
PATH=$PATH:$HOME/.local/bin:$HOME/bin

export PATH

export EDITOR=vim
export VISUAL=$EDITOR

source /etc/bash_completion.d/password-store
