#!/bin/bash

# Source global definitions
if [ -f /etc/bashrc ]; then
    . /etc/bashrc
fi

# Uncomment the following line if you don't like systemctl's auto-paging feature:
# export SYSTEMD_PAGER=

url_to_mpv() {
    if [ -z "$1" ]
    then
        echo 'mpvurl: error: missing url argument'
    else
        mpv --really-quiet $(youtube-dl -g "$1")
    fi
}

aspell_pipe_string() {
    printf $1 | aspell -a
}

alias ls='ls -h --color=auto --group-directories-first'
alias grep='grep --color=auto'
alias cp='cp -i -v'
alias mv='mv -i -v'
alias rm='rm -i -v'
alias ydl='youtube-dl --recode-video webm --prefer-free-formats -o "~/multimedia/videos/web/%(title)s.%(ext)s"'
alias mpvurl=url_to_mpv
alias spellcheck=aspell_pipe_string

if [ -e /usr/bin/vimx ]
then
    export EDITOR=vimx
    alias vim=vimx
else
    export EDITOR=vim
fi
export VISUAL=$EDITOR

source /etc/bash_completion.d/password-store
